services:
  proxy-service:
    hostname: proxy-service
    image: rivenbot/proxy-service:${PROXY_SERVICE_VERSION:-latest}
    ports: 
      - '8081:8081'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    network_mode: "host"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname==proxy-service-droplet
          - node.role==worker
    secrets:
      - ipv6
    environment:
      IPV6: /run/secrets/ipv6
  pgcr-crawler-service:
    hostname: pgcr-crawler-service
    image: rivenbot/pgcr-crawler-service:${PGCR_CRAWLER_SERVICE_VERSION:-latest}
    ports:
      - '8082:8082'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname==lair
          - node.role==manager
    secrets:
      - crawler_api_key
      - bungie_host
      - rabbitmq_url
    environment:
      BUNGIE_API_KEY_FILE: /run/secrets/crawler_api_key
      BUNGIE_HOST_FILE: /run/secrets/bungie_host
      RABBITMQ_URL_FILE: /run/secrets/rabbitmq_url
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:4.0.7-management
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5 
    deploy:
      placement:
        constraints:
          - node.hostname==lair
          - node.role==manager
  redis:
    hostname: redis
    image: redis:7.0.11
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1m
      timeout: 20s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.hostname==lair
          - node.role==manager
secrets:
  ipv6:
    external: true
  crawler_api_key:
    external: true
  bungie_host:
    external: true
  rabbitmq_url:
    external: true
