name: Docker Stack Deploy

on:
  workflow_call:
    inputs:
      proxy-service-version:
        required: false 
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PROXY_SERVICE_VERSION: ${{ inputs.proxy-service-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Riven-of-a-Thousand-Servers/rivenbot-deployments
          token: ${{ secrets.TOKEN }}

      - name: Debugging
        run: |
          pwd
          echo $USER
          docker --version
      
      - name: Docker Stack Deploy
        run: |
          docker stack deploy --detach=false -c docker-stack.yml rivenbot-stack

