name: Docker Stack Deploy

on:
  workflow_call:
    inputs:
      api-service-version:
        required: false
        type: string
      proxy-service-version:
        required: false 
        type: string
      pgcr-crawler-service-version:
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      TOKEN:
        required: true 

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    env:
      API_SERVICE_VERSION: ${{ inputs.api-service-version }}
      PROXY_SERVICE_VERSION: ${{ inputs.proxy-service-version }}
      PGCR_CRAWLER_SERVICE_VERSION: ${{ inputs.pgcr-crawler-service-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Riven-of-a-Thousand-Servers/rivenbot-deployments
          token: ${{ secrets.TOKEN }}
      - name: Docker Login
        run: |
          mkdir -p /tmp/docker-config
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker --config /tmp/docker-config login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Stack Deploy
        run: |
          docker --config /tmp/docker-config stack deploy --with-registry-auth --detach=false -c docker-stack.yml rivenbot-stack
